### ISSUE TITLE
trained model unzip failure

### ISSUE THREAD

**Issue by YufanXia999** [SchubertLab/mvTCR_reproducibility#1]
Dear authors,

thank you very much for your work! I am unable to unzip the zipped and trained model from the link "https://doi.org/10.5281/zenodo.7215447" in the ReadMe Experiment section. If it is related to my OS, I am using macOS. 

Thank you for your time!

**Comment by drEast** [comment]
Hi,
Thanks for your interest in our method. 
Unfortunately, I was not able to reproduce this problem (downloaded file from link + unzipped without issues). I will ask a colleague with macOS to check. 
Best,
Felix

**Comment by drEast** [comment]
@DeepOzean, could you please have a look? Thanks

**Comment by YufanXia999** [comment]
Hi,

 thank you so much for your time! My mac shown "Error 79 – Inappropriate File Type or Format". I tried to unzip it using external unzip software or from terminal. None of it works. Thank you again!

Best regards,
Yufan

**Comment by drEast** [comment]
Hi Yufan,
We were able to reproduce this error on MacOs for some unzip programs.
I will update the upload in the following days with a more compatible zipped version. Since I require feedback from people from my lab with MacOS, this might take a couple of days. Sorry, for the inconvenience.
Best,
Felix
